---
- name: Install ngnix server
  hosts: web
  gather_facts: true
  become: true
  tasks:
   - name: Install nginx package
     apt:
      name: nginx
      update_cache: true
   - name: Install git
     apt:
      name: git
      update_cache: true
   - name: Cloner le repo
     git: #J'ai pris celui de César mais c'est juste parce que ça sert à rien d'en créer un autre
      name: "https://github.com/CesarLortet/TP-Final_DevOps-HTML-Cesar_Lortet.git"
      dest: /var/www/html/