---
- name: Install Ansible
  hosts: web
  gather_facts: true
  become: true
  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        update_cache: true
    - name: Install git
      apt:
        name: git
        update_cache: true
    - name: Clone git repository
      git:
        name: <repo-html>
        dest: /var/www/html/
